services:
  - type: web
    name: smart-parking-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    region: singapore  # Optional: closest region to India
    plan: free
